import os
OUT = r'E:\Hyper-CAD-BEV-Experiments\scripts\run_experiments.py'
lines = []
lines.append('import os, sys, csv, time, warnings')
lines.append('from pathlib import Path')
lines.append('warnings.filterwarnings("ignore")')
lines.append('')
lines.append('ROOT = Path(r"E:/Hyper-CAD-BEV-Experiments")')
lines.append('RD = ROOT / "experiments" / "results"')
lines.append('RD.mkdir(parents=True, exist_ok=True)')
lines.append('')
lines.append('def sv(fn, h, rows):')
lines.append('    fp = RD / fn')
lines.append('    with open(fp, "w", newline="", encoding="utf-8") as f:')
lines.append('        w = csv.writer(f); w.writerow(h)')
lines.append('        for r in rows: w.writerow(r)')
lines.append('    print(f"  CSV: {fp}")')
lines.append('')
lines.append('def pt(h, rows, t=""):')
lines.append('    if t: print(f"\\n{\"=\"*70}\\n  {t}\\n{\"=\"*70}")')
lines.append('    cw = [max(len(str(hdr)), max(len(str(r[i])) for r in rows)) for i,hdr in enumerate(h)]')
lines.append('    sp = \"+\" + \"+\".join(\"-\"*(w+2) for w in cw) + \"+\"')
lines.append('    print(sp)')
lines.append('    print(\"|\" + \"|\".join(f\" {str(hdr):{w}} \" for hdr,w in zip(h,cw)) + \"|\")')
lines.append('    print(sp.replace(\"-\",\"=\"))')
lines.append('    for r in rows: print(\"|\" + \"|\".join(f\" {str(v):{w}} \" for v,w in zip(r,cw)) + \"|\")')
lines.append('    print(sp)')
lines.append('')
lines.append('print(\"=\"*70)')
lines.append('print(\"  Hyper-CAD-BEV v6.5-Sparse: Complete Experimental Reproduction\")')
lines.append('print(\"=\"*70)')
lines.append('print()')
print('gen written')
